services:

  canin:
    image: rg.nl-ams.scw.cloud/canin-registry/canin-frontend:${IMAGE_TAG}
    restart: unless-stopped
    labels:
      - "traefik.http.services.canin.loadbalancer.server.port=80"
      - "traefik.http.routers.canin_http.entrypoints=web"
      - "traefik.http.routers.canin_http.rule=Host(`caninpremierelangue.fr`) || Host(`www.caninpremierelangue.fr`)"
      - "traefik.http.routers.canin_http.middlewares=canin_https"
      - "traefik.http.middlewares.canin_https.redirectscheme.scheme=https"
      - "traefik.http.routers.canin.entrypoints=websecure"
      - "traefik.http.routers.canin.rule=Host(`caninpremierelangue.fr`) || Host(`www.caninpremierelangue.fr`)"
      - "traefik.http.routers.canin.tls=true"
      - "traefik.http.routers.canin.tls.certresolver=myresolver"
      # add header for csrf
      - "traefik.http.middlewares.caninHeader.headers.customrequestheaders.HTTP_X_FORWARDED_PROTO=https"
    networks:
      network_canin_prod:

networks:
  network_canin_prod:
    external: true
