name: CI - Build and Push Docker Image

on:
  push:
    branches: [ "ci-cd" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}


      - name: Build Docker image
        run: docker build -t jjehl/canin-premiere-langue:${{ github.sha }} .

      - name: Push Docker image
        run: docker push jjehl/canin-premiere-langue:${{ github.sha }}

