name: CI - Build, Push and Deploy Docker Image

on:
  push:
    branches: [ "ci-cd" ]
  release:
    types: [created]

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set variables for push
        if: github.event_name == 'push'
        run: |
          echo "DEPLOY_ENV=re7" > version.env
          echo "IMAGE_TAG=${{ github.sha }}" >> version.env
      - name: Set variables for pull request
        if: github.event_name == 'pull_request'
        run: |
          echo "DEPLOY_ENV=re7" > version.env
          echo "IMAGE_TAG=${{ github.sha }}" >> version.env
      - name: Set variables for release
        if: github.event_name == 'release'
        run: |
          echo "DEPLOY_ENV=prod" > version.env
          echo "IMAGE_TAG=${{ github.event.release.tag_name }}" >> version.env
      - name: Upload code as artifact
        uses: actions/upload-artifact@v4
        with:
          name: code
          path: .

  build-and-push:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Download code artifact
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build Docker image
        run: docker build -t jjehl/canin-premiere-langue:${{ github.sha }} .
      - name: Push Docker image
        run: docker push jjehl/canin-premiere-langue:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    environment: prod
    steps:
      - name: Download code artifact
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .

      - name: Display variables
        run: |
          cat version.env

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_CANIN_HOST }}
          username: ${{ secrets.SSH_CANIN_USER }}
          key: ${{ secrets.SSH_CANIN_KEY }}
          source: >
            ./deploy/start_remote.sh,
            ./deploy/docker-compose-re7.yaml,
            ./deploy/docker-compose-prod.yaml,
            ./version.env,
            ./deploy/re7.env,
            ./deploy/prod.env
          target: /home/canin/
          port: ${{ secrets.SSH_CANIN_PORT }}
          overwrite: true

      - name: Start docker compose
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_CANIN_HOST }}
          username: ${{ secrets.SSH_CANIN_USER }}
          key: ${{ secrets.SSH_CANIN_KEY }}
          port: ${{ secrets.SSH_CANIN_PORT }}
          script: |
            cd deploy
            bash start_remote.sh ${{ env.DEPLOY_ENV }}