name: Deploy to Server

on:
  push:
    branches:
      - toto  # Déclenchement sur la branche `main`

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy deploy.sh to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: ./deploy.sh
          target: /path/to/destination/deploy.sh

      - name: Run deploy.sh on the server
        uses: appleboy/ssh-action@v0.1.11
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            chmod +x /path/to/destination/deploy.sh
            /path/to/destination/deploy.sh
