name: CI - Build, Push and Deploy Docker Image

on:
  push:
    branches: ["main" ]
  pull_request:
    branches: ["main"]
    types: [opened, synchronize, reopened]
  release:
    types: [published]


jobs:
  prepare:
    name: "Prepare code"
    runs-on: ubuntu-latest

    container:
      image: node:22-alpine

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build and set variables for push
        if: github.event_name == 'push'
        run: |
          echo "DEPLOY_ENV=re7" > version-front.env
          echo "IMAGE_TAG=${{ github.sha }}" >> version-front.env
          npm install
          npm run build
      - name: Build and set variables for pull request
        if: github.event_name == 'pull_request'
        run: |
          echo "DEPLOY_ENV=re7" > version-front.env
          echo "IMAGE_TAG=${{ github.sha }}" >> version-front.env
          npm install
          npm run build
      - name: Build and set variables for release
        if: github.event_name == 'release'
        run: |
          echo "DEPLOY_ENV=prod" > version-front.env
          echo "IMAGE_TAG=${{ github.event.release.tag_name }}" >> version-front.env
          npm install
          npm run build
      - name: Upload code as artifact
        uses: actions/upload-artifact@v4
        with:
          name: code
          path: |
            .

  build-and-push:
    name: "Make Docker images"
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Download code artifact
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .
      - name: Set IMAGE_TAG from version.env
        id: set-image-tag
        run: |
          source version-front.env
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
      - name: Login to Scaleway container Registry
        uses: docker/login-action@v2
        with:
          registry: rg.nl-ams.scw.cloud
          username: nologin
          password: ${{ secrets.SCW_SECRET_KEY }}
      - name: Build Docker image
        run: docker build -f deploy/Dockerfile -t rg.nl-ams.scw.cloud/canin-registry/canin-frontend:${{ env.IMAGE_TAG }} .
      - name: Push Docker image
        run: docker push rg.nl-ams.scw.cloud/canin-registry/canin-frontend:${{ env.IMAGE_TAG }}

  deploy:
    name: "Deploy on OVH"
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Download code artifact
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .
      - name: Set vars from version.env
        run: |
          source version-front.env
          echo "SSH_KEY_SECRET=ssh-key-${DEPLOY_ENV}" >> $GITHUB_ENV
          echo "VERSION_FILE=version-front-${DEPLOY_ENV}.env" >> $GITHUB_ENV
          echo "COMPOSE_FILE=docker-compose-${DEPLOY_ENV}.yaml" >> $GITHUB_ENV
      - name: Get scaleways secrets using scaleways credential
        uses: scaleway/action-scw-secret@v0
        with:
          secret-names: |
            /canin-server/secret-connect
            /canin-server/${{ env.SSH_KEY_SECRET }}
          access-key: ${{ secrets.SCW_ACCESS_KEY }}
          secret-key: ${{ secrets.SCW_SECRET_KEY }}
          default-project-id: ${{ secrets.SCW_DEFAULT_PROJECT_ID }}
          default-organization-id: ${{ secrets.SCW_DEFAULT_ORGANIZATION_ID }}
      - name: Set vars from scaleway
        run: |
          source version-front.env
          # Get ssh parameters from scaleway secrets
          SSH_HOST=$(echo "$SECRET_CONNECT" | jq -r ".SSH_HOST_${DEPLOY_ENV^^}")
          SSH_USER=$(echo "$SECRET_CONNECT" | jq -r ".SSH_USER_${DEPLOY_ENV^^}")
          SSH_PORT=$(echo "$SECRET_CONNECT" | jq -r ".SSH_PORT_${DEPLOY_ENV^^}")
          declare -n SSH_KEY_JSON="SSH_KEY_${DEPLOY_ENV^^}"
          SSH_KEY=$(echo "$SSH_KEY_JSON" | jq -r ".ssh_private_key")
          # export variables to be used in next steps
          echo "SSH_HOST=$SSH_HOST" >> $GITHUB_ENV
          echo "SSH_USER=$SSH_USER" >> $GITHUB_ENV
          echo "SSH_PORT=$SSH_PORT" >> $GITHUB_ENV
          echo "$SSH_KEY" > ssh_key
          cp version-front.env ${{ env.VERSION_FILE }}
      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USER }}
          key_path: ./ssh_key
          source: >
            ./deploy/${{ env.COMPOSE_FILE }},
            ./${{ env.VERSION_FILE }},
            ./deploy/start_remote.sh,
          target: /home/canin/
          port: ${{ env.SSH_PORT }}
          overwrite: true

      - name: Start docker compose
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USER }}
          key_path: ./ssh_key
          port: ${{ env.SSH_PORT }}
          script: |
            docker login rg.nl-ams.scw.cloud/canin-registry -u nologin --password-stdin <<< ${{ secrets.SCW_SECRET_KEY }}
            source ${{ env.VERSION_FILE }}
            cd deploy
            bash start_remote.sh $DEPLOY_ENV