name: CI - Build, Push and Deploy Docker Image

on:
  push:
    branches: [ "ci-cd" ]

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Upload code as artifact
        uses: actions/upload-artifact@v4
        with:
          name: code
          path: .

  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Download code artifact
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build Docker image
        run: docker build -t jjehl/canin-premiere-langue:${{ github.sha }} .
      - name: Push Docker image
        run: docker push jjehl/canin-premiere-langue:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download code artifact
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .
      - name: Copy deploy.sh to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.CANIN_PRIVATE_KEY }}
          source: ./deploy.sh
          target: /home/canin/deploy.sh
          port: ${{ secrets.SSH_PORT }}